Update dataMigration.yml

diff --git a/.github/workflows/dataMigration.yml b/.github/workflows/dataMigration.yml
--- a/.github/workflows/dataMigration.yml
+++ b/.github/workflows/dataMigration.yml
@@ -35,12 +35,12 @@ jobs:
       contents: write
 
     steps:
-      - name: Fail if this run was queued
-        run: |
-          if [ "${{ github.run_attempt }}" != "1" ]; then
-            echo "::error::Another workflow is already running for this Environment + SObject"
-            exit 1
-          fi
+    - name: Fail if this run was queued
+      run: |
+        if [ "${{ github.run_attempt }}" != "1" ]; then
+          echo "::error::Another workflow is already running for this Environment + SObject"
+          exit 1
+        fi
     # - name: Fail if another run is already in progress
       # env:
       #   GH_TOKEN: ${{ github.token }}
