Update dataMigration.yml

diff --git a/.github/workflows/dataMigration.yml b/.github/workflows/dataMigration.yml
--- a/.github/workflows/dataMigration.yml
+++ b/.github/workflows/dataMigration.yml
@@ -11,6 +11,10 @@ on:
         required: true
         description: 'Comma-separated list of SObject names (e.g. abc__c,def__c)'
         type: string
+
+concurrency:
+  group: ${{ github.workflow }}-${{ inputs.sobjects }}
+  cancel-in-progress: false
   
 # Environment variables
 # env:
@@ -31,7 +35,7 @@ jobs:
       contents: write
 
     steps:
-    - name: Fail if another run is already in progress
+    # - name: Fail if another run is already in progress
       # env:
       #   GH_TOKEN: ${{ github.token }}
       # run: |
@@ -49,32 +53,32 @@ jobs:
       #     echo "❌ Another run is already in progress. Failing."
       #     exit 1
       #   fi
-      run: |
-        echo "Checking for concurrent workflow runs..."
-        echo "Branch      : main"
-        echo "Environment : $CURRENT_ENV"
-        echo "SObjects    : $CURRENT_SOBJECTS"
+      # run: |
+      #   echo "Checking for concurrent workflow runs..."
+      #   echo "Branch      : main"
+      #   echo "Environment : $CURRENT_ENV"
+      #   echo "SObjects    : $CURRENT_SOBJECTS"
     
-        RUNNING=$(gh api \
-          "/repos/${{ github.repository }}/actions/workflows/dataMigration.yml/runs?branch=main" \
-          --jq ".workflow_runs[]
-            | select(.status == \"in_progress\")
-            | select(.id != ${{ github.run_id }})
-            | select(.event == \"workflow_dispatch\")
-            | select(
-                .inputs.environment == \"$CURRENT_ENV\" and
-                .inputs.sobjects == \"$CURRENT_SOBJECTS\"
-              )
-            | .id" | wc -l | tr -d '[:space:]')
+      #   RUNNING=$(gh api \
+      #     "/repos/${{ github.repository }}/actions/workflows/dataMigration.yml/runs?branch=main" \
+      #     --jq ".workflow_runs[]
+      #       | select(.status == \"in_progress\")
+      #       | select(.id != ${{ github.run_id }})
+      #       | select(.event == \"workflow_dispatch\")
+      #       | select(
+      #           .inputs.environment == \"$CURRENT_ENV\" and
+      #           .inputs.sobjects == \"$CURRENT_SOBJECTS\"
+      #         )
+      #       | .id" | wc -l | tr -d '[:space:]')
     
-        echo "Matching running workflows count: $RUNNING"
+      #   echo "Matching running workflows count: $RUNNING"
     
-        if (( RUNNING > 0 )); then
-          echo "❌ A workflow is already running with the same branch, environment, and sobjects."
-          exit 1
-        fi
+      #   if (( RUNNING > 0 )); then
+      #     echo "❌ A workflow is already running with the same branch, environment, and sobjects."
+      #     exit 1
+      #   fi
     
-        echo "✅ No conflicting run found. Proceeding."
+      #   echo "✅ No conflicting run found. Proceeding."
 
     # Checkout the repository
     - name: Checkout source code
